hey24/footsteps

app/models/hike.rb
app/models/marker.rb
app/models/request.rb
app/models/user.rb
db/migrate/20230306161012_create_hikes.rb
db/migrate/20230306161857_create_requests.rb
db/migrate/20230306162136_create_markers.rb
db/migrate/20230306163838_add_details_to_users.rb
db/schema.rb
test/models/hike_test.rb
test/models/marker_test.rb
test/models/request_test.rb

Models set up with related associations and validations

Setting up models

---

app/models/hike.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb

Updated validations, reg form and checked that validations and associations are working

Update reg form

---

db/schema.rb
db/seeds.rb

Added correct locations for hike

Put correct locations for map api in seed file

---

app/controllers/requests_controller.rb
app/views/requests/index.html.erb
config/routes.rb

Created request 2 CRUD methods, created requests folder and index file, added code for create method to add In show page

Create requests controller

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_starting_point_autocomplete.scss
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/javascript/controllers/starting_point_autocomplete_controller.js
app/views/shared/_search.html.erb
package.json
yarn.lock

does what it says on the tin.
+ created partial scss file.

added search function with autocomplete to map

---

Gemfile
Gemfile.lock
app/controllers/hikes_controller.rb
app/models/hike.rb
app/views/hikes/_form.html.erb
app/views/hikes/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20230308114221_create_active_storage_tables.active_storage.rb
db/schema.rb

Added cloudinary functionality

Added cloudinary functionality

---

app/assets/stylesheets/components/_starting_point_autocomplete.scss

search bar now centered and transparent.
nav bar removed

removed navbar and fixed search bar (from Index/maps)

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_hike_card_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/hikes/index.html.erb
app/views/hikes/show.html.erb
app/views/shared/_hike_card_index.html.erb

- Show page basic structure is there
- It pulls information from the seed and the create new Hike form
- x out of x Hikers changes based on users in the Hike
-  Date says TBC if blank (which it always is on creation currently - there's no option to add date in the form which I think there should be)
- Confirmed icon changes and says confirmed/not confirmed based on true or false status

styled show page and added functionality for the icons

---

app/views/hikes/show.html.erb

added navigation link to showpage

created simple link to all hikes from show page

---

app/assets/stylesheets/components/_hike_marker.scss
app/assets/stylesheets/components/_index.scss
app/views/hikes/_hiker_marker.html.erb

removed blue pill background
changed colour of hiker icon via css
tried to keep size of icon consistent with Figma

hiker icon changes

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_loginform.scss
app/assets/stylesheets/components/_signupform.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Styled login page and signup page to make it look a little bit nicer

---

app/assets/stylesheets/components/_index.scss

Fixed semi colon bug in index scss"

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/hikes_controller.rb
app/views/hikes/show.html.erb

- Flow of pending button etc. should work now

made pending flow work

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/hikes_controller.rb
app/controllers/pages_controller.rb
app/views/hikes/_form.html.erb
app/views/hikes/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

See commits as I committed a lot this time

Show page stuff

---

app/assets/stylesheets/application.scss
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/index.js
app/views/hikes/_form.html.erb
package.json
yarn.lock

Added flatpickr into new stimulus controller to include date and time

Added flatpickr and update new hike form to include date and time

---

app/controllers/hikes_controller.rb
app/controllers/requests_controller.rb
app/controllers/users_controller.rb
app/models/hike.rb
app/models/user.rb
app/views/users/show.html.erb

Hikes are now completed if:
- The date of the Hike has passed
- The Hike was confirmed
A users completed Hikes are now also pulled in their profile page

added hikes completed functionality

---

app/assets/stylesheets/pages/_show.scss
app/controllers/chatrooms_controller.rb
app/views/hikes/show.html.erb
config/routes.rb

Fixed chatroom path to hike/hike_id/chatrooms
added correct button
added please confirm date button if not confirmed

Fixed Chatrooms routes

---

app/views/hikes/show.html.erb

When hike full cannot join hike

---

app/assets/stylesheets/components/_footer.scss

fixed footer plus button

---

app/assets/stylesheets/components/_message.scss
app/assets/stylesheets/pages/_chatroom.scss
app/assets/stylesheets/pages/_index.scss
app/views/chatrooms/index.html.erb

- Removed boostraps default styling
- Styled entire chat page

Styled chatpage to remove bootstrap default structure

---

app/views/pages/home.html.erb
public/404.html
public/500.html

Made 404 error page custom
Made 500 error page custom
Fixed navbar bug in homepage

made 404 and 500 error pages custom

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

- Updated seed
- fixed navbar wording
- moved carousel up

Seedchanges

---

app/models/user.rb

Profile completed hikes

---

app/assets/stylesheets/pages/_profile.scss
app/views/users/show.html.erb
db/seeds.rb

- Updated layout of profile page
- updated bio of both ben and linnea user
- Updated amount of requests and completed hikes from ben

Seedprofileupdate

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_profile.scss
app/views/layouts/application.html.erb

- Made background 100% no matter the height of the page

Fixed background to fit entire page

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

- Update to alignment of content on the homepage
- Colour of button on hover has been updated to not go transparent
- Footer add button aligned centrally and removed small gap that was present when looking on different mobile devices

Correct homepage alignment
